
ALTER TABLE public.call_sessions
  ADD COLUMN IF NOT EXISTS ip TEXT,
  ADD COLUMN IF NOT EXISTS geo_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS geo_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS geo_accuracy DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS geo_city TEXT,
  ADD COLUMN IF NOT EXISTS geo_region TEXT,
  ADD COLUMN IF NOT EXISTS geo_country TEXT,
  ADD COLUMN IF NOT EXISTS consent_recording BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS recording_path TEXT,
  ADD COLUMN IF NOT EXISTS has_paid BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS call_sessions_created_at_idx
  ON public.call_sessions (created_at DESC);
